import pandas as pd
df=pd.read_csv("digital_behaviour.csv")
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df[["Instagram_Minutes","YouTube_Minutes"]].describe())
print(df[["Instagram_Minutes","Date"]])
print(df["Instagram_Minutes"].sum())
print(df["Study_Minutes"].mean())
print(df["YouTube_Minutes"].max())
print(df[df["Instagram_Minutes"]>100][["Instagram_Minutes","Study_Minutes"]])
print(df[df["Instagram_Minutes"]>180])
#print(df[df["Instagram_Minutes"]-df["Study_Minutes"]])
